batch_size: 20
datasets:
  git: https://github.com/lucasncabral/mlgit-datasets.git
labels:
  git: https://github.com/lucasncabral/mlgit-labels.git
models:
  git: https://github.com/lucasncabral/mlgit-models.git
storages:
  s3h:
    mlgit-bucket:
      aws-credentials:
        profile: null
      endpoint-url: null
      region: us-east-1
