batch_size: 20
datasets:
  git: git@github.com:lucasncabral/mlgit-datasets.git
labels:
  git: ''
models:
  git: ''
storages:
  s3h:
    ml-git-qa-us-east-1:
      aws-credentials:
        profile: null
      endpoint-url: null
      region: us-east-1
