batch_size: 20
datasets:
  git: git@github.com:lucasncabral/mlgit-datasets.git
labels:
  git: git@github.com:lucasncabral/mlgit-datasets.git
models:
  git: git@github.com:lucasncabral/mlgit-datasets.git
storages:
  s3h:
    mlgit-bucket:
      aws-credentials:
        profile: null
      endpoint-url: null
      region: us-east-1
